### ISSUE TITLE
Cannot register Capella metamodels

### ISSUE THREAD

**Issue by szarnyasg** [mondo-project/mondo-hawk#28]
Followup from #24:

I tried to load the [Capella](https://www.polarsys.org/capella/) metamodel. This model has circular dependencies: for example, [CapellaCommon.ecore](https://git.polarsys.org/c/capella/capella.git/tree/m2/plugins/org.polarsys.capella.core.data.def/model/CapellaCommon.ecore#n25) and [CapellaCore.ecore](https://git.polarsys.org/c/capella/capella.git/tree/m2/plugins/org.polarsys.capella.core.data.def/model/CapellaCore.ecore#n274) depend on each other and they also have circular dependencies with [Requirement.ecore](https://git.polarsys.org/c/capella/capella.git/tree/m2/plugins/org.polarsys.capella.core.data.def/model/Requirement.ecore).

![image](https://cloud.githubusercontent.com/assets/1402801/11905353/5243db2c-a5c6-11e5-95e5-487ac790b1f7.png)

First I added the [eMDE.ecore](https://git.polarsys.org/c/kitalpha/kitalpha.git/tree/emde/plugins/org.polarsys.kitalpha.emde/model/eMDE.ecore) metamodel (which does not have any dependencies) with success. Then I tried to add the ModellingCore.ecore file. Interestingly, the error message was missing the eMDE.ecore file:

```
Adding metamodel(s)...
Adding metamodels in: /home/szarnyasg/git/capella-mm/org.polarsys.kitalpha.emde/model/eMDE.ecore to store
ADDING METAMODELS: 
ADDING: 3 METAMODEL NODES! (took ~0sec)
Added metamodel(s).
Updating Hawk...

!ENTRY org.hawk.ui2 1 0 2015-12-18 20:39:22.381
!MESSAGE updating indexer: 
Performing optional post-sync operations.

!ENTRY org.hawk.ui2 1 0 2015-12-18 20:39:22.381
!MESSAGE same revision, incrementing check timer: 16 -> 32 (max: 512)
Updated Hawk (success). 0s0ms
Adding metamodel(s)...
Adding metamodels in: /home/szarnyasg/git/capella-mm/org.polarsys.capella.common.data.core.gen/model/ModellingCore.ecore to store
ADDING METAMODELS: 
ADDING: attribute dependency from http://www.polarsys.org/capella/common/core/0.8.0 to http://www.eclipse.org/emf/2002/Ecore
EReference ownedExtensions has type ElementExtension which is in a package not registered yet, reverting all changes to this package registration, please register package with uri: file:/home/szarnyasg/git/capella-mm/org.polarsys.kitalpha.emde/model/eMDE.ecore first
1 METAMODEL NODES! (took ~0sec)
Added metamodel(s).
```

I suspect the real reason behind this is circular dependencies.

**Comment by bluezio** [comment]
I'm looking into this a bit more now. Where is that `ModellingCore.ecore` file? It doesn't seem to be in the kitalpha repository :-/.

**Comment by szarnyasg** [comment]
It's in the Capella repository: https://git.polarsys.org/c/capella/capella.git/tree/common/plugins/org.polarsys.capella.common.data.core.gen/model

**Comment by bluezio** [comment]
Interesting :-). At first, I got this message while trying to register the ModellingCore.ecore file:

    ADDING: EClass ModelElementhas supertype platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ExtensibleElement which is in a package not registered yet, reverting all changes to this package registration, please register package with uri: platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore first

That's the classic case of an `.ecore` file that has `platform:/` URLs, so I changed it to a nsURI-based reference, and then I got your message:

    EReference ownedExtensions has type ElementExtension which is in a package not registered yet, reverting all changes to this package registration, please register package with uri: file:/home/antonio/src/kitalpha/emde/plugins/org.polarsys.kitalpha.emde/model/eMDE.ecore first

The interesting thing in all this is that `ModellingCore.ecore` does not have `ownedExtensions` in it, but rather the original `eMDE.ecore` file. This sounds like a bug.

**Comment by bluezio** [comment]
I've debugged this a bit more and I have a first version of a fix, but I'd like to talk to Kostas tomorrow first. 

The issue seems to be in how we found the URL for the supertypes, references and attribute types when the class, reference or attribute `x` is in a different resource: in those cases, we used the substring of `x.getUri()` up to the `#` character. If `x` was in the same resource, we simply used the package URL.

The problem is that `x.getUri()` reports a `file:/` URL for some inherited `EAttribute`s in `ModellingCore.ecore`, and Hawk could not find those URLs in its metamodel index (as we index EMF metamodels by the nsURI of the `EPackage`).

Making Hawk use the package nsURI all the time (regardless of whether it is in the same resource or not) fixes this problem: I've been able to register `ModellingCore.ecore` just fine after it. However, I'd like to know why we had that code at all in the first place: maybe it's needed for some corner case.
