### ISSUE TITLE
Hawk incompatible with Epsilon 1.5 interim releases

### ISSUE THREAD

**Issue by kolovos** [mondo-project/mondo-hawk#42]
In [1] I removed of a number of interfaces and classes to simplify the module inheritance structure in Epsilon. In particular, I deleted the IEolExecutableModule interface, which broke Hawk in a couple of places. The attached patch replaces IEolExecutableModule with IEolModule and works for me. Shall I commit/push these changes?

[1] https://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git/commit/?id=4091010457cbba410c31755901a221f29850e680

Patch: [org.hawk.epsilon.patch.txt](https://github.com/mondo-project/mondo-hawk/files/628841/org.hawk.epsilon.patch.txt)

**Comment by bluezio** [comment]
Thanks for the patch! However, with the current target platform (which points to Epsilon 1.4 stable) EPLQueryEngine wouldn't compile (since an EplModule was not an IEolModule).

Would there be any workaround to keep the current target platform happy, while also being forward compatible with the latest Epsilon source?

If not, I'd rather stay on Epsilon 1.4 stable just so we may release Hawk 1.1 without having to wait for Epsilon 1.5 - we haven't had any major features added since 1.4 stable yet AFAIK.

**Comment by kolovos** [comment]
I can't think of a workaround that wouldn't partly re-introduce the former inheritance hierarchy I'm afraid. No problem from my side; this can wait until 1.5 is released.

**Comment by bluezio** [comment]
Thanks! I've changed the title to clarify this and help us remember when 1.5 is released.

**Comment by bluezio** [comment]
This has been fixed in ca98a602355bd4da719936e79851b17feae32269.
